## Some clarifications about the PBH test for reachability, controllability and stabilizabilty

As we have discussed in class, the key concept when it comes to state-transfer for a discrete-time linear system
$$
    x_{t+1}=Ax_t+Bu_t
$$
is **reachability**, i.e. the ability to steer the system state from $x_0=0$ to any $x_{\rm tgt}$ at some future time $t$.

The basic analysis, that you have also done in the basic course (although for a continuous-time system), is that a system is reachable if and only if the observability matrix 

$$
\mathcal{C}_n = \begin{pmatrix} A^{n-1}B & A^{n-2}B & \cdots & AB & B\end{pmatrix}
$$

has full rank. A nice by-product of the proof of this statement is that we know what whenever the system is reachable, you reach every target state in exact $n$ steps (where $n$ is the system order). Of course, this statement is only valid if you do not have any constraints on $x_t$ and $u_t$, and the control may be far from optimal in other aspects.

If you only have a single input, then the controllability matrix is square and you can check that it has full rank by computing its determinant. However, when the system has more inputs, checking for full rank becomes more complicated (at least by hand). Moreover, if the system is not reachable, the controllability matrix gives you no direct insight into whether the system is controllable or stabilizable.

The PBH test is much more helpful in this respect. We will also see that it is a very useful theoretical tool.

The PBH test states that a linear system is **unreachable** if and only if there is a vector $w\neq 0$ and a scalar $\lambda$ such that
$$
    w^{\top}A = \lambda w^{\top}, \qquad w^{\top}B=0
$$
Hence if the system is reachable, there can be no solution $(w, \lambda)$ to these equations.

The naming of variables in the PBH test is no coincidence: $\lambda$ is indeed an eigenvalue of $A$. 

Hence, to verify the PBH test by pen-and-paper, you first compute the eigenvalues $\lambda_i$ of $A$. For each of these, you compute the corresponding vector $w_i$ from $w_i^{\top}A=\lambda w_i^{\top}$ and test if it also satisfies $w_i^{\top}B=0$. If you can find any such combination $(\lambda_i, w_i)$, the system is unreachable.

As we mentioned on the lectures, $w$ defines directions in the state space in which we cannot control the state vector. In particular, $z_t = w^{\top}x_t$ satisfies
$$
    z_{t+1} = w^{\top}x_{t+1}=w^{\top}(Ax_t + Bu_t) = w^{\top}Ax_t = \lambda w^{\top}x_t = \lambda z_t
$$
Therefore, if we find $(\lambda_i, w_i)$ that satisfy the equations of the PBH test, it is fine if $\vert \lambda_i\vert<1$, since the dynamics that we cannot control will be asymptotically stable. If every $\lambda$ that satisfies the PBH equations has magnitude less than one, we call the system stabilizable. If all $\lambda_i$ that satisfy the PBH equations are equal to zero, the system is controllable. If any $\lambda_i$ that satisfies the PBH equation has magnitude greater than one, then we are in trouble. The system is unreachable, and the part of the state vector that we cannot control grows exponentially ("is unstable").

**Note.** How can we claim that $\lambda$ is an eigenvalue of $A$? Assuming that you are familiar with the standard right eigenvectors
$$
    Av = \lambda v
$$
we can tranpose the first PBH equation
$$
    (w^{\top}A)^{\top}=(\lambda w^{\top})^{\top} \Rightarrow A^{\top} w = \lambda w
$$
Hence, $w$ is a "standard" right eigenvector of $A^{\top}$. But a classic result from linear algebra (see the appendix of the lecture notes) states that $A$ and $A^{\top}$ have the same eigenvalues. Hence, $\lambda$ in the PBH equations is indeed an eigenvalue of $A$.

This discussion also shows how we can perform the PBH test numerically: we compute the eigenvalues $\lambda_i$ and eigenvectors $w_i$ of $A^{\top}$, and then check if any of these eigenvectors satisfy $w_i^{\top}B=0$. If they do, then the magnitude of the corresponding $\lambda_i$'s determine if the system is controllable, stabilizable, or unreachable. Let us try this technique on the systems in Exercise 1.5 (please also try to solve them by the paper-and-pen method described above!)

In [2]:
import numpy as np

In [3]:
# Define system matrices for 1.5 (a)
A=np.array([[1,1],[1,-1]]); B=np.array([[1],[1]]); 
print(f'A={A}'); print(f'B={B}')

A=[[ 1  1]
 [ 1 -1]]
B=[[1]
 [1]]


In [4]:
# Compute controllability matrix
C2=np.hstack((A@B, B))
print('Controllability matrix')
print(C2) 
print(f'has determinant {np.linalg.det(C2)} and is therefore of full rank.')

Controllability matrix
[[2 1]
 [0 1]]
has determinant 2.0 and is therefore of full rank.


In [5]:
# PBH approach
# Compute eigenvalues and eigenvectors of A^T, perform PBH test
(eigs,W)=np.linalg.eig(A.T)
lam1=eigs[0]; w1=W[:,0]
print(f'Eigenvalue lambda={lam1} has w^TB={w1.T@B}')
lam2=eigs[1]; w2=W[:,1]
print(f'Eigenvalue lambda={lam2} has w^TB={w2.T@B}')
# Since none of the w satisfy w^TB=0, the system is reachable

Eigenvalue lambda=1.414213562373095 has w^TB=[1.30656296]
Eigenvalue lambda=-1.4142135623730951 has w^TB=[0.5411961]


In [6]:
# Define system matrices for 1.5 (b)
A=np.array([[3,1],[-2.5,-0.5]]); B=np.array([[1],[-1]]); 
print(f'A={A}'); print(f'B={B}')

A=[[ 3.   1. ]
 [-2.5 -0.5]]
B=[[ 1]
 [-1]]


In [7]:
# Compute controllability matrix
C2=np.hstack((A@B, B))
print('Controllability matrix')
print(C2) 
print(f'has determinant {np.linalg.det(C2)} and is therefore not full rank.')

Controllability matrix
[[ 2.  1.]
 [-2. -1.]]
has determinant 0.0 and is therefore not full rank.


In [8]:
# PBH approach
# Compute eigenvalues and eigenvectors of A^T, perform PBH test
(eigs,W)=np.linalg.eig(A.T)
lam1=eigs[0]; w1=W[:,0]
print(f'Eigenvalue lambda={lam1} has w^TB={w1.T@B}')
lam2=eigs[1]; w2=W[:,1]
print(f'Eigenvalue lambda={lam2} has w^TB={w2.T@B}')
print('Since the magnitude of this eigenvalue is less than one, the system is stabilziable.')
# Since none of the w satisfy w^TB=0, the system is reachable

Eigenvalue lambda=2.0 has w^TB=[0.55708601]
Eigenvalue lambda=0.5 has w^TB=[0.]
Since the magnitude of this eigenvalue is less than one, the system is stabilziable.


In [9]:
# Define system matrices for 1.5 (c)
A=np.array([[2,0],[-0.5,0.5]]); B=np.array([[0],[1]]); 
print(f'A={A}'); print(f'B={B}')

A=[[ 2.   0. ]
 [-0.5  0.5]]
B=[[0]
 [1]]


In [10]:
# Compute controllability matrix
C2=np.hstack((A@B, B))
print('Controllability matrix')
print(C2) 
print(f'has determinant {np.linalg.det(C2)} and is therefore not full rank.')

Controllability matrix
[[0.  0. ]
 [0.5 1. ]]
has determinant 0.0 and is therefore not full rank.


In [11]:
# PBH approach
# Compute eigenvalues and eigenvectors of A^T, perform PBH test
(eigs,W)=np.linalg.eig(A.T)
lam1=eigs[0]; w1=W[:,0]
print(f'Eigenvalue lambda={lam1} has w^TB={w1.T@B}')
print('Since the magnitude of this eigenvalue is greater than one, the system is unreachable and neither controllable nor stabilizable.')
lam2=eigs[1]; w2=W[:,1]
print(f'Eigenvalue lambda={lam2} has w^TB={w2.T@B}')
# Since none of the w satisfy w^TB=0, the system is reachable

Eigenvalue lambda=2.0 has w^TB=[0.]
Since the magnitude of this eigenvalue is greater than one, the system is unreachable and neither controllable nor stabilizable.
Eigenvalue lambda=0.5 has w^TB=[0.9486833]


As we discussed above, any initital value $x_0$ with $z_0 = w^{\top}x_0 \neq 0$ will grow exponentially. Clearly, 
$$
    x_0=w_1=\begin{pmatrix}
    1\\0
    \end{pmatrix}
$$
has $w_1^{\top}x_0 = w_1^{\top}w_1\neq 0$ (in fact, it is equal to one, since the computed eigenvectors have unit norm). Let's simulate the system with this initial value.

In [12]:
x0=W[:,0]
x1=A@x0; print(f'x1={x1}')
x2=A@x1; print(f'x2={x2}')
x3=A@x2; print(f'x3={x3}')

x1=[ 2.  -0.5]
x2=[ 4.   -1.25]
x3=[ 8.    -2.625]


Please feel free to try these simulations for the controllable (but not reachable) system. 

Finally, to make the point that the controllability matrix is not always easy to use by hand when we have more than one input, let us add another input to the system in 1.5(a). 

In [13]:
# Define system matrices for 1.5 (a)
A=np.array([[1,1],[1,-1]]); B=np.array([[1, 1],[1, 0]]); 
print(f'A={A}'); print(f'B={B}')

A=[[ 1  1]
 [ 1 -1]]
B=[[1 1]
 [1 0]]


Of course, since the system is controllable already with the first input, it will be (at least) controllable also with an additional input. Let us determine and print the controllability matrix

In [14]:
C2=np.hstack((A@B,B))
print('Controllability matrix')
print(C2) 

Controllability matrix
[[2 1 1 1]
 [0 1 1 0]]


Since the matrix is no longer square, we cannot check that is has the full rank by the determinant test. It is still easy to see that the controllability matrix has full rank here (for example, the new $B$ matrix, which is the last block of the controllability matrix is of full rank (it is square with non-zero determinant) so $C_2$ is too). Hence, with these two inputs, the controllability matrix shows that the system is actually even reachable (not only controllable).

If we use the following matrices that describe the dynamics of a four-tank system, it is less obvious to deduce controllability from simply looking at the controllability matrix

In [15]:
A = np.array([
    [0.9921, 0, 0.0206, 0],
    [0, 0.9945, 0, 0.0165],
    [0, 0, 0.9793, 0],
    [0, 0, 0, 0.9835]
])

B = np.array([
    [0.0415, 0.0002],
    [0.0001, 0.0313],
    [0, 0.0237],
    [0.0155, 0]
])
C4=np.hstack((A@A@A@B, A@A@B, A@B, B))
print('Controllability matrix')
print(C4) 

Controllability matrix
[[0.0405242  0.00161839 0.04084689 0.00115933 0.04117215 0.00068664
  0.0415     0.0002    ]
 [0.00084883 0.03078639 0.00060478 0.03095665 0.0003552  0.03112785
  0.0001     0.0313    ]
 [0.         0.02225849 0.         0.02272898 0.         0.02320941
  0.         0.0237    ]
 [0.01474534 0.         0.01499272 0.         0.01524425 0.
  0.0155     0.        ]]


On a computer, of course, we can simply compute the rank numerically

In [16]:
np.linalg.matrix_rank(C4)

np.int64(4)

Still, you can hopefully appreciate that the PBH test is a useful complement to your other tools :)

Just a final note. When you have multiple inputs, $w^{\top}B$ will be a row vector with $m$ entries, and the condition $w^{\top}B=0$ means that all entries of this vector should be zero. I encourage you to redo the PBH test (numerically) for the system from 1.5(a) with two inputs that we considered above. You will see that that also the PBH test shows that the system is reachable (and not only controllable).
